---
# tasks file for hardware_setup
- name: Install nvidia driver to laptop
  ansible.builtin.apt:
      name: "{{ laptop_video_driver_package }}"
      state: present
      update_cache: true
  when: ansible_form_factor == "Notebook"
  tags:
    - videodriver
