---
# tasks file for system_setup
# Мозг себе взорвал, пока разобрался с json_query. Главное - следить за тем, какой тип данных скармливать следующему оператору
# https://jmespath.org/tutorial.html
# https://jmespath.org/specification.html#function-evaluation
# pip3 install jmespath-terminal далее - jpterm
- name: Hide pool's name from Thunar panel
  ansible.builtin.set_fact:
    devices_uuid: "{{ ansible_devices | json_query(jmesquery) }}"
  vars:
    jmesquery: "values(@)[].partitions.values(@)[].links[] | [?labels[].ends_with(@, 'pool')].uuids[]"
- name: Show all values for selected device name
  ansible.builtin.debug:
    var: devices_uuid
    verbosity: 4

- name: Adding lines in udev rules file for hiding partitions
  ansible.builtin.lineinfile:
    path: /etc/udev/rules.d/99-hidedrives.rules
    line: SUBSYSTEM=="block", ENV{ID_FS_UUID}=="{{ item }}", ENV{UDISKS_IGNORE}="1"
    mode: "0644"
    create: true
  loop: "{{ devices_uuid }}"
# This thing doesn't work. ansible not opening ssh with X11Forward key
# Worth checking out later
# -name: Setup mouse middle button
# ansible.builtin.command:
# xmodmap -e "pointer = 1 0 3 4 5 6 7 2"
# register: my_output # <-Registers the command output.
# changed_when: my_output.rc != 0 # <-Uses the return code to define when the task has changed.

# - name: Ensure a locale is installed
#   ansible.builtin.apt:
#     name: en_NZ.utf8
#     state: present

- name: Setup time locale
  ansible.builtin.command: update-locale LC_TIME=en_NZ.utf8
  register: my_output # <-Registers the command output.
  changed_when: my_output.rc != 0 # <-Uses the return code to define when the task has changed.

- name: Check directory xfce-config exists
  ansible.builtin.stat:
    path: /home/cableman/.config/xfce4/xfconf/xfce-perchannel-xml/
  register: xfce_conf_dir_exists

- name: Copy files for xfce
  ansible.builtin.copy:
    src: xfce-perchannel-xml/{{ item }}
    dest: /home/cableman/.config/xfce4/xfconf/xfce-perchannel-xml/
    owner: cableman
    group: cableman
    mode: "0664"
    force: true
    backup: true
  with_items:
    - 'keyboards.xml'
    - 'keyboard-layout.xml'
    - 'thunar-volman.xml'
    - 'thunar.xml'
    - 'xfce4-keyboard-shortcuts.xml'
    - 'xfce4-panel.xml'
    - 'xfce4-taskmanager.xml'
    - 'xfwm4.xml'
    - 'xsettings.xml'
  when: xfce_conf_dir_exists.stat.exists

- name: Copy .bashrc and zshrc
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/cableman/
    owner: cableman
    group: cableman
    mode: "0644"
    force: true
  with_items:
    - '.bashrc'
    - '.bash_aliases'
    - '.zshrc'
    - '.p10k.zsh'

- name: Ensure ZSH set as default shell
  ansible.builtin.user:
    name: cableman
    shell: /usr/bin/zsh
    state: present
  tags:
    - 'zsh'

- name: Copy ohmyzsh.sh
  ansible.builtin.copy:
    src: oh-my-zsh.sh
    dest: /home/cableman/.oh-my-zsh/
    owner: cableman
    group: cableman
    mode: "0644"
    force: true
  tags:
    - zsh

- name: Delete file for disable help information on welcome ssh console
  ansible.builtin.file:
    path: /etc/update-motd.d/10-help-text
    state: absent
    force: true

- name: Edit /etc/bluetooth/input.conf for IdleTimeout=0
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/input.conf
    regexp: 'IdleTimeout='
    line: IdleTimeout=0
    mode: "0644"
    create: false
  notify: Bluetooth_restart

- name: Edit /etc/bluetooth/main.conf for FastConnectable=true
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: 'FastConnectable ='
    line: FastConnectable = true
    mode: "0644"
    create: false
  notify: Bluetooth_restart

- name: Remove unattended-upgrades
  ansible.builtin.apt:
    package:
      - unattended-upgrades
    state: absent

- name: Config auto upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: false
  loop:
    - { regexp: 'APT::Periodic::Update-Package-Lists', line: 'APT::Periodic::Update-Package-Lists "0";' }
    - { regexp: 'APT::Periodic::Unattended-Upgrade', line: 'APT::Periodic::Unattended-Upgrade "0";' }
  tags:
    - auto_upgrades

# TODO disable blocking after 30 min IdleTimeout
# xmodmap -e "pointer = 1 0 3 4 5 6 7 2" to autostart
# просмотреть и применить все заметки  Linux Install
