---
# handlers file for system_setup
- name: Bluetooth_restart
  ansible.builtin.service:
    name: bluetooth
    state: restarted

- name: update_grub
  ansible.builtin.command: update-grub2
#  register: my_output # <-Registers the command output.
#  changed_when: my_output.rc != 0 # <-Uses the return code to define when the task has changed.
